import React from "react";

export const MedicalDisclaimer = () => (
  <div className="space-y-6 text-[#003636] font-barlow">
    <div className="p-4 bg-red-50 border border-red-100 rounded-2xl mb-6">
      <p className="text-sm font-bold text-red-600">
        IMPORTANT: This service is NOT for medical emergencies. If you are experiencing a medical emergency, call 911 or your local emergency services immediately.
      </p>
    </div>

    <section>
      <h2 className="text-xl font-bold mb-3">1. No Medical Advice</h2>
      <p className="text-sm leading-relaxed text-muted-foreground">
        The information provided by EvidenceMD.ai, including AI-generated clinical summaries, research insights, and imaging interpretations, is for informational and educational purposes only. It does not constitute professional medical advice, diagnosis, or treatment.
      </p>
    </section>

    <section>
      <h2 className="text-xl font-bold mb-3">2. Clinical Judgment Required</h2>
      <p className="text-sm leading-relaxed text-muted-foreground">
        EvidenceMD is a tool designed to assist healthcare professionals. It is not a substitute for the professional judgment of a healthcare provider. Always seek the advice of a physician or other qualified health provider with any questions you may have regarding a medical condition.
      </p>
    </section>

    <section>
      <h2 className="text-xl font-bold mb-3">3. AI Limitations</h2>
      <p className="text-sm leading-relaxed text-muted-foreground">
        The AI models used by EvidenceMD may occasionally produce inaccurate, incomplete, or biased information. Users must independently verify all information generated by the platform before using it in any clinical setting.
      </p>
    </section>

    <section>
      <h2 className="text-xl font-bold mb-3">4. No Doctor-Patient Relationship</h2>
      <p className="text-sm leading-relaxed text-muted-foreground">
        Use of EvidenceMD does not create a doctor-patient relationship between you and EvidenceMD or its affiliates. Patient users should use the information as a basis for discussion with their own healthcare providers.
      </p>
    </section>

    <section>
      <h2 className="text-xl font-bold mb-3">5. Accuracy of Information</h2>
      <p className="text-sm leading-relaxed text-muted-foreground">
        While we strive to provide accurate and up-to-date information, medical knowledge is constantly evolving. We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or suitability of the information provided.
      </p>
    </section>
  </div>
);
